# Generated by Django 5.1.4 on 2026-09-30 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('doc_type', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=64)),
                ('license', models.TextField()),
                ('url', models.URLField(blank=True, max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('checksum', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'corpus_documents',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(max_length=200)),
                ('ddinter_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('nlem_listed', models.BooleanField(default=False)),
                ('nlem_section', models.CharField(blank=True, max_length=32)),
                ('nlem_level_of_care', models.CharField(blank=True, max_length=16)),
                ('nlem_dosage_forms', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'drugs',
            },
        ),
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_version', models.CharField(max_length=200)),
                ('kb_version', models.CharField(max_length=32)),
                ('git_sha', models.CharField(blank=True, max_length=64)),
                ('llm_mode', models.CharField(max_length=32)),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evaluation_runs',
            },
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=16)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('prompt_version', models.CharField(blank=True, max_length=32)),
                ('fallback_level', models.IntegerField(default=0)),
                ('degraded_retrieval', models.BooleanField(default=False)),
                ('correlation_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'explanations',
            },
        ),
        migrations.CreateModel(
            name='KbVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32, unique=True)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'kb_versions',
            },
        ),
        migrations.CreateModel(
            name='LlmCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('node', models.CharField(max_length=48)),
                ('model', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(blank=True, max_length=32)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('est_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('latency_ms', models.FloatField(default=0)),
                ('fallback_level', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=24)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'llm_calls',
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('endpoint', models.CharField(db_index=True, max_length=200)),
                ('method', models.CharField(max_length=8)),
                ('status_code', models.IntegerField()),
                ('latency_ms', models.FloatField()),
                ('user_id', models.IntegerField(null=True)),
                ('llm_calls', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'request_logs',
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('tool', models.CharField(max_length=32)),
                ('args_summary', models.TextField()),
                ('result_summary', models.TextField()),
                ('latency_ms', models.FloatField()),
                ('status', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tool_calls',
            },
        ),
        migrations.CreateModel(
            name='CorpusChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_path', models.CharField(max_length=400)),
                ('page', models.IntegerField(null=True)),
                ('text', models.TextField()),
                ('text_hash', models.CharField(max_length=64)),
                ('faiss_row', models.IntegerField(db_index=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.corpusdocument')),
            ],
            options={
                'db_table': 'corpus_chunks',
            },
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('Major', 'Major'), ('Moderate', 'Moderate'), ('Minor', 'Minor'), ('Unknown', 'Unknown')], max_length=16)),
                ('source', models.CharField(default='DDInter', max_length=32)),
                ('source_record_id', models.CharField(max_length=64)),
                ('drug_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.drug')),
                ('drug_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.drug')),
                ('kb_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kbversion')),
            ],
            options={
                'db_table': 'drug_interactions',
            },
        ),
        migrations.CreateModel(
            name='DuplicationFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('item_labels', models.JSONField(default=list)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.drug')),
            ],
            options={
                'db_table': 'duplication_findings',
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=16)),
                ('metric', models.CharField(max_length=4)),
                ('passed', models.BooleanField()),
                ('score', models.FloatField(null=True)),
                ('detail', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.evaluationrun')),
            ],
            options={
                'db_table': 'evaluation_results',
            },
        ),
        migrations.CreateModel(
            name='InteractionFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField()),
                ('drug_a_name', models.CharField(max_length=200)),
                ('drug_b_name', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('Major', 'Major'), ('Moderate', 'Moderate'), ('Minor', 'Minor'), ('Unknown', 'Unknown')], max_length=16)),
                ('source', models.CharField(max_length=32)),
                ('source_record_id', models.CharField(max_length=64)),
                ('priority', models.CharField(max_length=8)),
                ('rule_id', models.CharField(max_length=8)),
                ('evidence_status', models.CharField(default='PENDING', max_length=16)),
                ('review_status', models.CharField(default='pending', max_length=24)),
                ('drug_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.drug')),
                ('drug_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.drug')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.druginteraction')),
                ('kb_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.kbversion')),
            ],
            options={
                'db_table': 'interaction_findings',
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='ExplanationClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_key', models.CharField(max_length=16)),
                ('text', models.TextField()),
                ('source_type', models.CharField(max_length=16)),
                ('support_score', models.FloatField(null=True)),
                ('support_span', models.TextField(blank=True)),
                ('kept', models.BooleanField()),
                ('drop_reason', models.CharField(blank=True, max_length=200)),
                ('chunk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.corpuschunk')),
                ('explanation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.explanation')),
                ('interaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.druginteraction')),
                ('finding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.interactionfinding')),
            ],
            options={
                'db_table': 'explanation_claims',
            },
        ),
        migrations.CreateModel(
            name='EvidenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=16)),
                ('score', models.FloatField(null=True)),
                ('retrieval_mode', models.CharField(max_length=16)),
                ('chunk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.corpuschunk')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='api.interactionfinding')),
                ('kb_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.kbversion')),
            ],
            options={
                'db_table': 'evidence_links',
            },
        ),
        migrations.CreateModel(
            name='DrugAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('alias_normalized', models.CharField(db_index=True, max_length=200)),
                ('alias_type', models.CharField(choices=[('generic', 'generic'), ('synonym', 'synonym'), ('brand', 'brand'), ('abbreviation', 'abbreviation'), ('misspelling', 'misspelling')], max_length=16)),
                ('source', models.CharField(max_length=64)),
                ('is_synthetic', models.BooleanField(default=False)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='api.drug')),
                ('kb_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kbversion')),
            ],
            options={
                'db_table': 'drug_aliases',
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='kb_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kbversion'),
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=64)),
                ('license', models.TextField()),
                ('url', models.URLField(blank=True, max_length=500)),
                ('retrieved_at', models.DateTimeField()),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('is_synthetic', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('kb_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='api.kbversion')),
            ],
            options={
                'db_table': 'data_sources',
            },
        ),
        migrations.AddField(
            model_name='corpusdocument',
            name='kb_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kbversion'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('raw_text_hash', models.CharField(max_length=64)),
                ('age_band', models.CharField(default='unknown', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('CHECKED', 'CHECKED'), ('EXPLAINED', 'EXPLAINED'), ('AWAITING_PHARMACIST', 'AWAITING_PHARMACIST'), ('IN_REVIEW', 'IN_REVIEW'), ('REVIEWED', 'REVIEWED'), ('CLEAR', 'CLEAR')], default='CHECKED', max_length=24)),
                ('injection_flag', models.BooleanField(default=False)),
                ('injection_patterns', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(default='CLEAR', max_length=8)),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('lines_ignored', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kb_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.kbversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PharmacistReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ACKNOWLEDGE', 'ACKNOWLEDGE'), ('ESCALATE', 'ESCALATE'), ('REQUEST_MORE_EVIDENCE', 'REQUEST_MORE_EVIDENCE'), ('MARK_FOR_FOLLOW_UP', 'MARK_FOR_FOLLOW_UP')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('correlation_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duplication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.duplicationfinding')),
                ('finding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.interactionfinding')),
                ('kb_version_seen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.kbversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.prescription')),
            ],
            options={
                'db_table': 'pharmacist_reviews',
            },
        ),
        migrations.AddField(
            model_name='interactionfinding',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='api.prescription'),
        ),
        migrations.AddField(
            model_name='explanation',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='api.prescription'),
        ),
        migrations.AddField(
            model_name='duplicationfinding',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplications', to='api.prescription'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('correlation_id', models.CharField(max_length=64)),
                ('actor', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=48)),
                ('entity', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('kb_version', models.CharField(max_length=32)),
                ('timestamp', models.CharField(max_length=40)),
                ('prev_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='api.prescription')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['prescription_id', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('graph', models.CharField(max_length=16)),
                ('node', models.CharField(max_length=48)),
                ('status', models.CharField(max_length=16)),
                ('latency_ms', models.FloatField()),
                ('summary', models.TextField(blank=True)),
                ('state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.prescription')),
            ],
            options={
                'db_table': 'agent_steps',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('brand_normalized', models.CharField(db_index=True, max_length=200)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('kb_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kbversion')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('raw_span', models.TextField()),
                ('matched_text', models.CharField(blank=True, max_length=200)),
                ('method', models.CharField(choices=[('exact', 'exact'), ('fuzzy', 'fuzzy'), ('llm_choice', 'llm_choice'), ('pharmacist', 'pharmacist'), ('unresolved', 'unresolved')], max_length=16)),
                ('confidence', models.FloatField(null=True)),
                ('needs_confirmation', models.BooleanField(default=False)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('drug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.prescription')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.product')),
            ],
            options={
                'db_table': 'prescription_items',
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drug')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.product')),
            ],
            options={
                'db_table': 'product_ingredients',
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=32)),
                ('template', models.TextField()),
                ('template_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prompt_versions',
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='uniq_prompt_version')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='api.session'),
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(choices=[('MAJOR_INTERACTION', 'MAJOR_INTERACTION'), ('RED_FLAG', 'RED_FLAG'), ('PEDIATRIC', 'PEDIATRIC'), ('DOSING_REQUEST', 'DOSING_REQUEST'), ('UNRESOLVED_DRUG', 'UNRESOLVED_DRUG'), ('PROMPT_INJECTION', 'PROMPT_INJECTION'), ('CONFLICT', 'CONFLICT'), ('INSUFFICIENT_EVIDENCE', 'INSUFFICIENT_EVIDENCE'), ('DECISION_REQUEST', 'DECISION_REQUEST')], max_length=32)),
                ('trigger_rule_id', models.CharField(max_length=16)),
                ('detail', models.CharField(max_length=500)),
                ('status', models.CharField(default='OPEN', max_length=16)),
                ('created_by', models.CharField(max_length=64)),
                ('correlation_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='api.prescription')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.session')),
            ],
            options={
                'db_table': 'escalations',
            },
        ),
        migrations.CreateModel(
            name='SessionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.prescription')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.session')),
            ],
            options={
                'db_table': 'session_messages',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TriageRuleHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=8)),
                ('priority', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=200)),
                ('input_summary', models.TextField()),
                ('result', models.CharField(max_length=200)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_hits', to='api.prescription')),
            ],
            options={
                'db_table': 'triage_rule_hits',
            },
        ),
        migrations.CreateModel(
            name='ChunkDrugMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='api.corpuschunk')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drug')),
            ],
            options={
                'db_table': 'chunk_drug_mentions',
                'constraints': [models.UniqueConstraint(fields=('chunk', 'drug'), name='uniq_chunk_drug')],
            },
        ),
        migrations.AddIndex(
            model_name='druginteraction',
            index=models.Index(fields=['kb_version', 'drug_a', 'drug_b'], name='drug_intera_kb_vers_5e0757_idx'),
        ),
        migrations.AddConstraint(
            model_name='druginteraction',
            constraint=models.CheckConstraint(condition=models.Q(('drug_a__lt', models.F('drug_b'))), name='interaction_canonical_order'),
        ),
        migrations.AddConstraint(
            model_name='druginteraction',
            constraint=models.UniqueConstraint(fields=('drug_a', 'drug_b', 'source', 'kb_version'), name='uniq_interaction'),
        ),
        migrations.AddConstraint(
            model_name='drug',
            constraint=models.UniqueConstraint(fields=('kb_version', 'normalized_name'), name='uniq_drug_norm_per_kb'),
        ),
        migrations.AddConstraint(
            model_name='auditlog',
            constraint=models.UniqueConstraint(fields=('prescription', 'seq'), name='uniq_audit_seq'),
        ),
    ]
