# Generated by Django 5.1.4 on 2026-09-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fulltext_and_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkdrugmention',
            name='via',
            field=models.CharField(default='direct', max_length=64),
        ),
    ]
